name: Create and publish a Docker image

on:
  push:
    branches: 
      - 'main'
      - 'cicd'

env:
  CW_NAME: ${{ github.event.repository.name }}

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
      deployments: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Build
        run: |
          python compile.py

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false

      - name: Upload artifacts
        id: upload-release-asset
        uses: softprops/action-gh-release@v1
        with:
          files: |
            build/src/report.pdf
